# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b8767dcea8354f26a6a9d3c321fe048b78b15d12f49f05a4ca87991c0ee4d9b694455e0d542fa1a6830efbc46f5c17ca79c18827a404aba0f133f70c7e554b4

test:
  secret_key_base: bcc0892ef956dff185d340f828cd41e8db62331e6d294ab359439ffa79bf35463ec0127be03d16ee3f92f09ff8e0da9543e5c18b6542a88fc3fbafeb1ecdc3cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
